server:
  port: 8761  # Port standard Eureka

eureka:
  client:
    register-with-eureka: false  # Ne pas s'enregistrer soi-même
    fetch-registry: false        # Ne pas récupérer le registre
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: discovery-service

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics